#! /bin/bash -x

CPP_STANDARD=c++17
INCLUDES=("-Iinclude/" "-Itests/tools/Catch2/src/"
	"-Itests/tools/trompeloeil/include/" "-IDebug/generated-includes/")

clang-tidy "$@" -header-filter="^include/|^src/" -- -std=${CPP_STANDARD} ${INCLUDES[*]}
